version: '3'
services:
  hacknews:
    container_name: hackernews
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./subscriptions:/subscriptions"
      - "./pdf:/pdf"
    command: 'node /subscriptions/hackernews.js'