name: hackernews
on:
  push:
  repository_dispatch:
    types: manual
  schedule:
    - cron: '0 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate pdf
        run: |
          docker-compose up
      - name: email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: hackernews
          body: A bright new day!
          to: yuqing.ji@outlook.com
          from: yuqing.ji@outlook.com
          attachments: pdf/hackernews.pdf