name: hackernews
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate pdf
        run: |
          docker-compose up
      - uses: actions/upload-artifact@v1
        with:
          name: hackernews.pdf
          path: pdf/hackernews.pdf