name: hackernews
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate pdf
        run: |
          docker-compose up
      - uses: actions/upload-artifact@v1
        with:
          name: hackernews.pdf
          path: pdf/hackernews.pdf
      - name: email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: hackernews
          to: yuqing.ji@outlook.com
          from: yuqing.ji@outlook.com
          attachments: pdf/hackernews.pdf